**Feature Engineering**

In [1]:
# Libraries
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
# Dataset
data = {
    "Age": [22, 28, 35, 42, 50, 24, np.nan, 38, 60, 31],

    "Salary": [
        25000, 35000, 45000, 55000, 65000,
        np.nan, 40000, 50000, 200000, 38000
    ],

    "Gender": [
        "Male", "Female", "Female", "Male", "Male",
        "Female", "Male", None, "Female", "Male"
    ],

    "City": [
        "Hyderabad", "Delhi", "Mumbai", "Hyderabad", "Delhi",
        "Mumbai", None, "Delhi", "Mumbai", "Hyderabad"
    ],

    "Date": [
        "2026-01-10", "2026-02-15", "2026-03-20", "2026-04-25",
        "2026-05-12", "2026-06-18", "2026-07-05", "2026-08-14",
        "2026-09-22", "2026-10-30"
    ],

    "Purchase_Amount": [
        5000, 7000, 8500, 9000, 12000,
        6000, 7500, 10000, 15000, 8000
    ],

    "Experience": [1, 3, 5, 8, 12, 2, 4, 7, 15, 5],

    "Rating": [3.5, 4.0, 4.5, 4.2, 4.8, 3.8, 4.1, 4.4, 4.9, 4.0]
}

df = pd.DataFrame(data)

print("Original Dataset:")
display(df)

print("Dataset Information:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())

Original Dataset:

,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating
0,22.0,25000.0,Male,Hyderabad,2026-01-10,5000,1,3.5
1,28.0,35000.0,Female,Delhi,2026-02-15,7000,3,4.0
2,35.0,45000.0,Female,Mumbai,2026-03-20,8500,5,4.5
3,42.0,55000.0,Male,Hyderabad,2026-04-25,9000,8,4.2
4,50.0,65000.0,Male,Delhi,2026-05-12,12000,12,4.8
5,24.0,NaN,Female,Mumbai,2026-06-18,6000,2,3.8
6,NaN,40000.0,Male,None,2026-07-05,7500,4,4.1
7,38.0,50000.0,None,Delhi,2026-08-14,10000,7,4.4
8,60.0,200000.0,Female,Mumbai,2026-09-22,15000,15,4.9
9,31.0,38000.0,Male,Hyderabad,2026-10-30,8000,5,4.0

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              9 non-null      float64
 1   Salary           9 non-null      float64
 2   Gender           9 non-null      object
 3   City             9 non-null      object
 4   Date             10 non-null     object
 5   Purchase_Amount  10 non-null     int64
 6   Experience       10 non-null     int64
 7   Rating           10 non-null     float64
dtypes: float64(3), int64(2), object(3)
memory usage: 772.0+ bytes

Missing Values:
Age                1
Salary             1
Gender             1
City               1
Date               0
Purchase_Amount    0
Experience         0
Rating             0
dtype: int64

In [4]:
# Problem 1: Handling Missing Values
# Numerical columns
numerical_columns = df.select_dtypes(include=np.number).columns

df[numerical_columns] = df[numerical_columns].fillna(
    df[numerical_columns].mean()
)

# Categorical columns
categorical_columns = df.select_dtypes(include="object").columns

for column in categorical_columns:
    df[column] = df[column].fillna(df[column].mode()[0])

print("Missing Values After Cleaning:")
print(df.isnull().sum())

display(df)

Missing Values After Cleaning:
Age                0
Salary             0
Gender             0
City               0
Date               0
Purchase_Amount    0
Experience         0
Rating             0
dtype: int64

,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating
0,22.000000,25000.000000,Male,Hyderabad,2026-01-10,5000,1,3.5
1,28.000000,35000.000000,Female,Delhi,2026-02-15,7000,3,4.0
2,35.000000,45000.000000,Female,Mumbai,2026-03-20,8500,5,4.5
3,42.000000,55000.000000,Male,Hyderabad,2026-04-25,9000,8,4.2
4,50.000000,65000.000000,Male,Delhi,2026-05-12,12000,12,4.8
5,24.000000,61444.444444,Female,Mumbai,2026-06-18,6000,2,3.8
6,36.666667,40000.000000,Male,Delhi,2026-07-05,7500,4,4.1
7,38.000000,50000.000000,Male,Delhi,2026-08-14,10000,7,4.4
8,60.000000,200000.000000,Female,Mumbai,2026-09-22,15000,15,4.9
9,31.000000,38000.000000,Male,Hyderabad,2026-10-30,8000,5,4.0

In [5]:
# Problem 2: Feature Scaling
df["Salary_Before"] = df["Salary"]
df["Age_Before"] = df["Age"]

standard_scaler = StandardScaler()
minmax_scaler = MinMaxScaler()

df["Salary_Scaled"] = standard_scaler.fit_transform(
    df[["Salary"]]
)

df["Age_Scaled"] = minmax_scaler.fit_transform(
    df[["Age"]]
)

print("Before and After Scaling:")

display(
    df[
        [
            "Salary_Before",
            "Salary_Scaled",
            "Age_Before",
            "Age_Scaled"
        ]
    ]
)

Before and After Scaling:

   Salary_Before  Salary_Scaled  Age_Before  Age_Scaled
0   25000.000000  -7.650890e-01   22.000000    0.000000
1   35000.000000  -5.551560e-01   28.000000    0.157895
2   45000.000000  -3.452231e-01   35.000000    0.342105
3   55000.000000  -1.352901e-01   42.000000    0.526316
4   65000.000000   7.464283e-02   50.000000    0.736842
5   61444.444444  -1.527463e-16   24.000000    0.052632
6   40000.000000  -4.501896e-01   36.666667    0.385965
7   50000.000000  -2.402566e-01   38.000000    0.421053
8  200000.000000   2.908738e+00   60.000000    1.000000
9   38000.000000  -4.921762e-01   31.000000    0.236842

In [9]:
# Problem 3: Encoding Categorical Data
# Label Encoding Gender
label_encoder = LabelEncoder()

df["Gender_Encoded"] = label_encoder.fit_transform(
    df["Gender"]
)

print("Gender Encoding:")
display(df[["Gender", "Gender_Encoded"]])

Gender Encoding:

   Gender  Gender_Encoded
0    Male               1
1  Female               0
2  Female               0
3    Male               1
4    Male               1
5  Female               0
6    Male               1
7    Male               1
8  Female               0
9    Male               1

In [13]:
# One-Hot Encoding City
if "City" in df.columns:
    df = pd.get_dummies(df, columns=["City"], dtype=int)

print("Dataset After One-Hot Encoding City:")
display(df)

Dataset After One-Hot Encoding City:

,Age,Salary,Gender,Date,Purchase_Amount,Experience,Rating,Salary_Before,Age_Before,Salary_Scaled,Age_Scaled,Gender_Encoded,City_Delhi,City_Hyderabad,City_Mumbai
0,22.000000,25000.000000,Male,2026-01-10,5000,1,3.5,25000.000000,22.000000,-7.650890e-01,0.000000,1,0,1,0
1,28.000000,35000.000000,Female,2026-02-15,7000,3,4.0,35000.000000,28.000000,-5.551560e-01,0.157895,0,1,0,0
2,35.000000,45000.000000,Female,2026-03-20,8500,5,4.5,45000.000000,35.000000,-3.452231e-01,0.342105,0,0,0,1
3,42.000000,55000.000000,Male,2026-04-25,9000,8,4.2,55000.000000,42.000000,-1.352901e-01,0.526316,1,0,1,0
4,50.000000,65000.000000,Male,2026-05-12,12000,12,4.8,65000.000000,50.000000,7.464283e-02,0.736842,1,1,0,0
5,24.000000,61444.444444,Female,2026-06-18,6000,2,3.8,61444.444444,24.000000,-1.527463e-16,0.052632,0,0,0,1
6,36.666667,40000.000000,Male,2026-07-05,7500,4,4.1,40000.000000,36.666667,-4.501896e-01,0.385965,1,1,0,0
7,38.000000,50000.000000,Male,2026-08-14,10000,7,4.4,50000.000000,38.000000,-2.402566e-01,0.421053,1,1,0,0
8,60.000000,200000.000000,Female,2026-09-22,15000,15,4.9,200000.000000,60.000000,2.908738e+00,1.000000,0,0,0,1
9,31.000000,38000.000000,Male,2026-10-30,8000,5,4.0,38000.000000,31.000000,-4.921762e-01,0.236842,1,0,1,0

In [14]:
# Problem 4: Feature Creation
df["Total_Spending"] = (
    df["Salary"] + df["Purchase_Amount"]
)

print("After Creating Total_Spending:")

display(
    df[
        [
            "Salary",
            "Purchase_Amount",
            "Total_Spending"
        ]
    ]
)

After Creating Total_Spending:

          Salary  Purchase_Amount  Total_Spending
0   25000.000000             5000    30000.000000
1   35000.000000             7000    42000.000000
2   45000.000000             8500    53500.000000
3   55000.000000             9000    64000.000000
4   65000.000000            12000    77000.000000
5   61444.444444             6000    67444.444444
6   40000.000000             7500    47500.000000
7   50000.000000            10000    60000.000000
8  200000.000000            15000   215000.000000
9   38000.000000             8000    46000.000000

In [15]:
# Problem 5: Date Feature Extraction
df["Date"] = pd.to_datetime(df["Date"])

df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day
df["Weekday"] = df["Date"].dt.day_name()

print("Extracted Date Features:")

display(
    df[
        [
            "Date",
            "Year",
            "Month",
            "Day",
            "Weekday"
        ]
    ]
)

Extracted Date Features:

        Date  Year  Month  Day   Weekday
0 2026-01-10  2026      1   10  Saturday
1 2026-02-15  2026      2   15    Sunday
2 2026-03-20  2026      3   20    Friday
3 2026-04-25  2026      4   25  Saturday
4 2026-05-12  2026      5   12   Tuesday
5 2026-06-18  2026      6   18  Thursday
6 2026-07-05  2026      7    5    Sunday
7 2026-08-14  2026      8   14    Friday
8 2026-09-22  2026      9   22   Tuesday
9 2026-10-30  2026     10   30    Friday

In [16]:
# Problem 6: Age Binning
bins = [0, 25, 45, np.inf]

labels = [
    "Young",
    "Adult",
    "Senior"
]

df["Age_Group"] = pd.cut(
    df["Age"],
    bins=bins,
    labels=labels
)

print("Age Groups:")

display(
    df[
        [
            "Age",
            "Age_Group"
        ]
    ]
)

Age Groups:

         Age Age_Group
0  22.000000     Young
1  28.000000     Adult
2  35.000000     Adult
3  42.000000     Adult
4  50.000000    Senior
5  24.000000     Young
6  36.666667     Adult
7  38.000000     Adult
8  60.000000    Senior
9  31.000000     Adult

In [18]:
# Problem 7: Salary Outlier Detection Using IQR
Q1 = df["Salary"].quantile(0.25)
Q3 = df["Salary"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)

salary_outliers = df[
    (df["Salary"] < lower_limit) |
    (df["Salary"] > upper_limit)
]

print("Salary Outliers:")

display(salary_outliers)

Q1: 38500.0
Q3: 59833.333333333336
IQR: 21333.333333333336
Lower Limit: 6499.999999999996
Upper Limit: 91833.33333333334
Salary Outliers:

,Age,Salary,Gender,Date,Purchase_Amount,Experience,Rating,Salary_Before,Age_Before,Salary_Scaled,...,Gender_Encoded,City_Delhi,City_Hyderabad,City_Mumbai,Total_Spending,Year,Month,Day,Weekday,Age_Group
8,60.0,200000.0,Female,2026-09-22,15000,15,4.9,200000.0,60.0,2.908738,...,0,0,0,1,215000.0,2026,9,22,Tuesday,Senior

In [19]:
# Problem 8: Feature Interaction
df["Experience_Salary"] = (
    df["Experience"] * df["Salary"]
)

print("Experience and Salary Interaction:")

display(
    df[
        [
            "Experience",
            "Salary",
            "Experience_Salary"
        ]
    ]
)

Experience and Salary Interaction:

   Experience         Salary  Experience_Salary
0           1   25000.000000       2.500000e+04
1           3   35000.000000       1.050000e+05
2           5   45000.000000       2.250000e+05
3           8   55000.000000       4.400000e+05
4          12   65000.000000       7.800000e+05
5           2   61444.444444       1.228889e+05
6           4   40000.000000       1.600000e+05
7           7   50000.000000       3.500000e+05
8          15  200000.000000       3.000000e+06
9           5   38000.000000       1.900000e+05

In [23]:
# Problem 9: Feature Selection
numeric_df = df.select_dtypes(include=np.number)

# Calculate correlation with target variable
correlation = numeric_df.corr()["Purchase_Amount"].sort_values(ascending=False)

print("Correlation with Purchase Amount:")
print(correlation)

# Get absolute correlations excluding the target itself and removing NaNs (e.g., constant columns like Year)
feature_correlation = correlation.drop("Purchase_Amount").abs().dropna().sort_values()

print("\nFeature Importance Based on Correlation:")
print(feature_correlation)

# Identify the least important feature automatically
least_important = feature_correlation.idxmin()
print(f"\nLeast Important Feature to drop: '{least_important}'")

# Drop the least important feature
df_final = df.drop(columns=[least_important])

print("\nFinal Dataset:")
display(df_final)

Correlation with Purchase Amount:
Purchase_Amount      1.000000
Experience           0.984094
Age_Scaled           0.970692
Age                  0.970692
Age_Before           0.970692
Rating               0.936365
Experience_Salary    0.869569
Total_Spending       0.838910
Salary_Before        0.821102
Salary_Scaled        0.821102
Salary               0.821102
Month                0.498319
City_Mumbai          0.242062
Day                  0.226452
City_Delhi           0.094954
Gender_Encoded      -0.094954
City_Hyderabad      -0.343572
Year                      NaN
Name: Purchase_Amount, dtype: float64

Feature Importance Based on Correlation:
Gender_Encoded       0.094954
City_Delhi           0.094954
Day                  0.226452
City_Mumbai          0.242062
City_Hyderabad       0.343572
Month                0.498319
Salary               0.821102
Salary_Scaled        0.821102
Salary_Before        0.821102
Total_Spending       0.838910
Experience_Salary    0.869569
Rating               0.936365
Age_Before           0.970692
Age                  0.970692
Age_Scaled           0.970692
Experience           0.984094
Name: Purchase_Amount, dtype: float64

Least Important Feature to drop: 'Gender_Encoded'

Final Dataset:

,Age,Salary,Gender,Date,Purchase_Amount,Experience,Rating,Salary_Before,Age_Before,Salary_Scaled,...,City_Delhi,City_Hyderabad,City_Mumbai,Total_Spending,Year,Month,Day,Weekday,Age_Group,Experience_Salary
0,22.000000,25000.000000,Male,2026-01-10,5000,1,3.5,25000.000000,22.000000,-7.650890e-01,...,0,1,0,30000.000000,2026,1,10,Saturday,Young,2.500000e+04
1,28.000000,35000.000000,Female,2026-02-15,7000,3,4.0,35000.000000,28.000000,-5.551560e-01,...,1,0,0,42000.000000,2026,2,15,Sunday,Adult,1.050000e+05
2,35.000000,45000.000000,Female,2026-03-20,8500,5,4.5,45000.000000,35.000000,-3.452231e-01,...,0,0,1,53500.000000,2026,3,20,Friday,Adult,2.250000e+05
3,42.000000,55000.000000,Male,2026-04-25,9000,8,4.2,55000.000000,42.000000,-1.352901e-01,...,0,1,0,64000.000000,2026,4,25,Saturday,Adult,4.400000e+05
4,50.000000,65000.000000,Male,2026-05-12,12000,12,4.8,65000.000000,50.000000,7.464283e-02,...,1,0,0,77000.000000,2026,5,12,Tuesday,Senior,7.800000e+05
5,24.000000,61444.444444,Female,2026-06-18,6000,2,3.8,61444.444444,24.000000,-1.527463e-16,...,0,0,1,67444.444444,2026,6,18,Thursday,Young,1.228889e+05
6,36.666667,40000.000000,Male,2026-07-05,7500,4,4.1,40000.000000,36.666667,-4.501896e-01,...,1,0,0,47500.000000,2026,7,5,Sunday,Adult,1.600000e+05
7,38.000000,50000.000000,Male,2026-08-14,10000,7,4.4,50000.000000,38.000000,-2.402566e-01,...,1,0,0,60000.000000,2026,8,14,Friday,Adult,3.500000e+05
8,60.000000,200000.000000,Female,2026-09-22,15000,15,4.9,200000.000000,60.000000,2.908738e+00,...,0,0,1,215000.000000,2026,9,22,Tuesday,Senior,3.000000e+06
9,31.000000,38000.000000,Male,2026-10-30,8000,5,4.0,38000.000000,31.000000,-4.921762e-01,...,0,1,0,46000.000000,2026,10,30,Friday,Adult,1.900000e+05

In [24]:
# Save the Dataset
df_final.to_csv(
    "feature_engineered_dataset.csv",
    index=False
)

print("Dataset saved successfully!")

Dataset saved successfully!